version: 2
jobs:
  test:
    filters:
      branches:
        only:
          - master
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          command: 'npm install'
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          command: 'npm run test:once'

  build_and_deploy:
    filters:
      branches:
        only:
          - master
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          command: 'CI="" && npm run build'
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: sh deploy.sh

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test
      - build_and_deploy:
          requires:
            - test
