version: 2
jobs:
  test:
    filters:
      branches:
        only:
          - master
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          command: 'npm install'
      - run:
          command: 'npm run test:once'

  build_and_deploy:
    filters:
      branches:
        only:
          - master
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          command: 'CI="" && npm run build'
      - run: sh deploy.sh

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test
      - build_and_deploy:
          requires:
            - test
